import type { SiteConfig, Product } from "@/lib/types";

const ORIGIN_CE = "SHINOVA · China · CE/ISO 13485";

const labProducts: Product[] = [
  {
    id: "hemo-5diff",
    model: "Hemo 5100V",
    category: "HEMATOLOGIA",
    name: "Analisador Hematológico Veterinário Automático 5-Diff",
    shortName: "Hematologia 5-Diff",
    productUrl: "https://www.shinova.com/product/detailp/5-Diff-Fully-automatic-Veterinary-Hematology-Analyzer",
    images: [
      "/products/hemo-5diff.jpg",
      "/products/hemo-5diff-2.jpg",
      "/products/hemo-5diff-3.jpg",
      "/products/hemo-5diff-4.jpg",
      "/products/hemo-5diff-5.jpg",
    ],
    description: [
      "O Hemo 5100V é o analisador hematológico veterinário de topo da Shinova, com diferencial de 5 partes (5-Diff) por citometria de fluxo a laser combinada com impedância e colorimetria, diferenciação leucocitária precisa e resultados de maior exatidão que os métodos tradicionais.",
      "Inclui análise de reticulócitos (RET#, RET%, IRF), apoiando a avaliação da função medular e o diagnóstico e classificação de anemias. Ao todo são 37 parâmetros (25 de rotina, 6 de pesquisa e 3 de reticulócitos), com histogramas de RBC e PLT e scattergrams de WBC.",
      "Suporta múltiplas espécies (cães, gatos, equinos, bovinos, suínos e mais), com modos de sangue total, prédiluído e reticulócitos, além de modo felino dedicado para maior precisão. Throughput de até 60 amostras/hora, armazenamento de até 200.000 resultados e tela touch de 10,4\". Indicado para clínicas, hospitais, laboratórios e centros de pesquisa veterinária.",
    ],
    specs: [
      { label: "Aplicação", value: "Laboratório veterinário / hospital / pesquisa" },
      { label: "Tipo de diferencial", value: "5 partes + reticulócitos (37 parâmetros)" },
      { label: "Throughput", value: "Até 60 amostras/hora" },
      { label: "Volume de amostra", value: "Sangue total ≤ 15 µL / prédiluído ≤ 20 µL" },
      { label: "Display", value: 'Tela touch 10,4"' },
      { label: "Armazenamento", value: "Até 200.000 resultados" },
      { label: "Conectividade", value: "4× USB" },
      { label: "Espécies", value: "Multiespécie (cão, gato, equino, bovino, etc.)" },
      { label: "Tecnologia", value: "Citometria de fluxo a laser + impedância + colorimetria" },
      { label: "Ambiente de operação", value: "15–35 °C / 20–85% UR" },
      { label: "Garantia", value: "12 meses" },
      { label: "Origem", value: ORIGIN_CE },
    ],
  },
  {
    id: "hemo-3diff",
    model: "Hemo 3100V",
    category: "HEMATOLOGIA",
    name: "Analisador Hematológico Veterinário Automático 3-Diff",
    shortName: "Hematologia 3-Diff",
    productUrl: "https://www.shinova.com/product/detailp/3-Diff-Veterinary-Fully-automatic-Hematology-Analyzer",
    images: [
      "/products/hemo-3diff.jpg",
      "/products/hemo-3diff-2.jpg",
      "/products/hemo-3diff-3.jpg",
      "/products/hemo-3diff-4.jpg",
      "/products/hemo-3diff-5.jpg",
    ],
    description: [
      "O Hemo 3100V é o analisador hematológico veterinário totalmente automático da linha Shinova, com diferencial de 3 partes (3-Diff). Conta células pelo método de impedância elétrica e mede hemoglobina por método livre de cianeto, resultados estáveis e consistentes para hemograma completo.",
      "Sistema de alarme inteligente com mensagens em texto para anormalidades de WBC, RBC e PLT, facilitando a interpretação clínica e a identificação rápida de parâmetros alterados. São 21 parâmetros de rotina (WBC, RBC, HGB, PLT, MCV, MCH, MCHC, etc.) com histogramas de WBC, RBC e PLT.",
      "Traz parâmetros pré-configurados para 13 espécies (cães, gatos, equinos, bovinos, suínos, coelhos e mais) com 3 espécies personalizáveis, além de modos de sangue venoso e capilar. Throughput de até 40 amostras/hora, armazenamento de mais de 600.000 resultados, impressora térmica integrada, conectividade LIS/HIS e tela touch de 10,4\". Desenho compacto (apenas 0,12 m²).",
    ],
    specs: [
      { label: "Aplicação", value: "Laboratório veterinário / hospital / clínica" },
      { label: "Tipo de diferencial", value: "3 partes (3-Diff)" },
      { label: "Parâmetros", value: "21" },
      { label: "Throughput", value: "Até 40 amostras/hora" },
      { label: "Volume de amostra", value: "Sangue total 8,5 µL / prédiluído 20 µL" },
      { label: "Display", value: 'Tela touch 10,4"' },
      { label: "Armazenamento", value: "≥ 600.000 resultados" },
      { label: "Conectividade", value: "USB / Ethernet / serial" },
      { label: "Espécies", value: "13 pré-configuradas + 3 personalizáveis" },
      { label: "Impressora", value: "Térmica integrada" },
      { label: "Alimentação", value: "AC 100–240V, 50/60 Hz" },
      { label: "Garantia", value: "12 meses" },
      { label: "Origem", value: ORIGIN_CE },
    ],
  },
  {
    id: "chemo-120v",
    model: "Chemo 120V",
    category: "BIOQUÍMICA",
    name: "Analisador Bioquímico Veterinário Automático de Bancada",
    shortName: "Bioquímica Automática",
    productUrl: "https://www.shinova.com/product/detailp/Vet-Chemistry-Analyzer-Chemo-120V",
    images: [
      "/products/chemo-120v.jpg",
      "/products/chemo-120v-2.jpg",
      "/products/chemo-120v-3.jpg",
      "/products/chemo-120v-4.jpg",
      "/products/chemo-120v-5.jpg",
      "/products/chemo-120v-6.jpg",
      "/products/chemo-120v-7.jpg",
      "/products/chemo-120v-8.jpg",
    ],
    description: [
      "O Chemo 120V é o analisador bioquímico veterinário automático de bancada da linha Shinova, projetado para rotina laboratorial de clínicas e hospitais veterinários. Totalmente automático, com software dedicado à medicina veterinária e operação \"walk-away\": você carrega as amostras e o equipamento conduz o ciclo sozinho.",
      "Traz 8 perfis de animais pré-configurados e número ilimitado de perfis definidos pelo usuário, cobrindo cães, gatos, bovinos, equinos, peixes, roedores, suínos, coelhos e outros. Sistema de reagentes aberto (fechado sob demanda), com micro-volumes de amostra e reagente que reduzem o custo por teste.",
      "Throughput de até 100 testes por hora, programação simples e posições de amostra e reagente intercambiáveis. Software multilíngue. Ideal para laboratórios veterinários que precisam de bioquímica clínica e imunoturbidimetria com alto rendimento e mínima intervenção do operador.",
    ],
    specs: [
      { label: "Tipos de animais", value: "Cão, gato, bovino, peixe, equino, roedor, suíno, coelho, etc." },
      { label: "Tipo de teste", value: "Bioquímica clínica, imunoturbidimetria" },
      { label: "Modos analíticos", value: "Ponto final, dois pontos, cinético" },
      { label: "Operação", value: "Automática, acesso randômico, prioridade STAT" },
      { label: "Posições de amostra", value: "9" },
      { label: "Volume de amostra", value: "3–45 µL (ajuste 0,1 µL)" },
      { label: "Posições de reagente", value: "26 (refrigeradas 4–15 °C)" },
      { label: "Volume de reagente", value: "R1 180–450 µL / R2 3–250 µL" },
      { label: "Posições de reação", value: "90 cubetas (10 por tira)" },
      { label: "Cubeta", value: "Caminho óptico 5 mm" },
      { label: "Temperatura de reação", value: "37 °C" },
      { label: "Comprimentos de onda", value: "8 (340–700 nm)" },
      { label: "Faixa de absorbância", value: "0–3,500 Abs (resolução 0,0001)" },
      { label: "Alimentação", value: "AC 110V/220V, 50/60 Hz" },
      { label: "Dimensões", value: "630×480×510 mm · 70 kg" },
      { label: "Origem", value: ORIGIN_CE },
    ],
  },
  {
    id: "chemo-port",
    model: "ChemoDisk 6",
    category: "BIOQUÍMICA PORTÁTIL",
    name: "Analisador Bioquímico Veterinário Portátil por Disco",
    shortName: "Bioquímica Portátil",
    productUrl: "https://www.shinova.com/product/detailp/Portable-Full-automatic-Veterinary-Chemistry-Analyzer",
    images: [
      "/products/chemo-port.jpg",
      "/products/chemo-port-2.jpg",
      "/products/chemo-port-3.jpg",
      "/products/chemo-port-4.jpg",
      "/products/chemo-port-5.jpg",
      "/products/chemo-port-6.jpg",
      "/products/chemo-port-7.jpg",
      "/products/chemo-port-8.jpg",
    ],
    description: [
      "O ChemoDisk 6 é o analisador bioquímico veterinário portátil da Shinova, baseado em tecnologia de microfluídica (rotores/discos integrados). Pesa apenas 4,3 kg e entrega resultado em cerca de 10 minutos a partir de microcoleta de sangue, ideal para atendimento à beira do paciente, clínicas de campo e pronto-atendimento.",
      "Funciona com discos de reagente liofilizado prontos para uso: uma única etapa de adição de amostra (100 µL de sangue total, soro ou plasma), sem necessidade de calibração, o equipamento lê automaticamente a calibração de fábrica. Sistema inteligente de controle de qualidade monitora cada amostra para garantir a precisão.",
      "Mais de dez tipos de disco cobrem painéis completos: check-up de saúde (19 itens), função hepática e renal, pré-anestésico, casos graves/agudos, eletrólitos, inflamação canina e felina, grandes animais, aves/répteis e diabetes, entre outros. Tela touch de 7\", Wi-Fi/Ethernet/USB com suporte a LIS e impressora térmica integrada.",
    ],
    specs: [
      { label: "Interface", value: 'Tela touch LCD 7"' },
      { label: "Tipo de amostra", value: "Sangue total com anticoagulante, soro e plasma" },
      { label: "Volume de amostra", value: "0,1 mL (100 µL)" },
      { label: "Calibração", value: "Dispensa calibração (lê calibração de fábrica)" },
      { label: "Controle de qualidade", value: "Sistema inteligente por amostra" },
      { label: "Tempo de análise", value: "~10 minutos" },
      { label: "Disco de reagente", value: "Diluente + reagente liofilizado" },
      { label: "Precisão de temperatura", value: "37 °C ± 0,1 °C" },
      { label: "Armazenamento", value: "≥ 50.000 resultados + QC" },
      { label: "Conectividade", value: "Wi-Fi, Ethernet, 2× USB, suporte LIS" },
      { label: "Impressora", value: "Térmica integrada" },
      { label: "Peso", value: "4,3 kg (portátil)" },
      { label: "Alimentação", value: "AC 100–240V, 50–60 Hz / DC 24V" },
      { label: "Painéis disponíveis", value: "14 (check-up, hepático/renal, pré-anestésico, agudos, eletrólitos, inflamação, aves/répteis, diabetes, etc.)" },
      { label: "Origem", value: ORIGIN_CE },
    ],
  },
  {
    id: "bg-800a",
    model: "BG-800A",
    category: "GASOMETRIA",
    name: "Analisador de Gases Sanguíneos e Eletrólitos Veterinário",
    shortName: "Gasometria / Eletrólitos",
    productUrl: "https://www.shinova.com/product/detailp/Blood-Gas-Electrolyte-Analyzer-BG-800A",
    images: [
      "/products/bg-800a.jpg",
      "/products/bg-800a-2.jpg",
      "/products/bg-800a-3.jpg",
      "/products/bg-800a-4.jpg",
      "/products/bg-800a-5.jpg",
      "/products/bg-800a-6.jpg",
      "/products/bg-800a-7.jpg",
      "/products/bg-800a-8.jpg",
    ],
    description: [
      "O BG-800A é o analisador veterinário de gases sanguíneos e eletrólitos da linha Shinova, pensado para UTI, centro cirúrgico e emergência, onde decisões rápidas dependem de pH, gases e eletrólitos confiáveis à beira do paciente. Aceita seringa ou capilar e trabalha com sangue total, soro, plasma, dialisato e líquor.",
      "Usa eletrodos próprios livres de manutenção e sistema de fluidos de longa duração, com cartucho de calibração tudo-em-um, pré-aquecimento de reagentes e amostra, e alarme de validade/resíduo do cartucho. Tela touch colorida de alta resolução, interface amigável, detector humano por infravermelho e gestão de dados completa.",
      "A configuração BG-800A mede pH, pCO₂, pO₂ e hematócrito (Hct); a plataforma BG-800 possui variantes que adicionam K⁺, Na⁺, Cl⁻, Ca⁺⁺, lactato e glicose, com opção de controle de qualidade automático. Bateria de backup, impressora térmica integrada e leitor de código de barras, com baixo custo por teste.",
    ],
    specs: [
      { label: "Tipo de amostra", value: "Sangue total, soro, plasma, dialisato, líquor" },
      { label: "Parâmetros (BG-800A)", value: "pH, pCO₂, pO₂, Hct" },
      { label: "Variantes da plataforma", value: "+ K⁺, Na⁺, Cl⁻, Ca⁺⁺, lactato, glicose e QC automático" },
      { label: "Faixa pH", value: "6,000–9,000" },
      { label: "Faixa pCO₂", value: "5,0–200,0 mmHg" },
      { label: "Faixa pO₂", value: "0–800,0 mmHg" },
      { label: "Eletrólitos", value: "K⁺ 0,5–10 · Na⁺ 50–200 · Cl⁻ 20–200 · Ca⁺⁺ 0,1–5 mmol/L" },
      { label: "Hematócrito", value: "12,0–65,0 %" },
      { label: "Volume de amostra", value: "95 µL (total) / 50 µL (capilar)" },
      { label: "Calibração", value: "Automática, 1 e 2 pontos, programável" },
      { label: "Armazenamento", value: "> 10.000 resultados" },
      { label: "Display", value: 'Tela touch TFT 10,4"' },
      { label: "Bateria", value: "Níquel-metal hidreto 3,0 Ah (backup)" },
      { label: "Impressora", value: "Térmica integrada 70 mm" },
      { label: "Leitor de código de barras", value: "Até 14 tipos" },
      { label: "Dimensões", value: "400×574×344 mm · 18 kg" },
      { label: "Alimentação", value: "100–240V, 50/60 Hz, 150 VA" },
      { label: "Origem", value: ORIGIN_CE },
    ],
  },
  {
    id: "cl-202b",
    model: "CL-202B",
    category: "COAGULAÇÃO",
    name: "Coagulômetro Veterinário",
    shortName: "Coagulômetro",
    productUrl: "https://www.shinova.com/product/detailp/Veterinary-Coagulometer-CL-202B",
    images: [
      "/products/cl-202b.jpg",
      "/products/cl-202b-2.jpg",
      "/products/cl-202b-3.jpg",
      "/products/cl-202b-4.jpg",
      "/products/cl-202b-5.jpg",
      "/products/cl-202b-6.jpg",
    ],
    description: [
      "O CL-202B é o coagulômetro veterinário da linha Shinova, equipamento de bancada para avaliação de hemostasia e tempos de coagulação no laboratório veterinário. Opera por método fotométrico (óptico) com fonte de lâmpada halógena e agitação magnética na cubeta de medição, garantindo leitura estável.",
      "Conta com dois canais de medição e incubadora integrada a 37 °C ± 0,2 °C para manter as amostras na temperatura fisiológica durante o ensaio. São 32 posições de amostra (2×16) e 4 posições de reagente (2×2), com entrada por teclado de membrana e impressora térmica integrada (papel de 58 mm) para emissão imediata dos laudos.",
      "Display LCD de 5,7\", operação em português/inglês (outros idiomas sob demanda) e desenho compacto (30×40×15 cm, 5,5 kg) que cabe em qualquer bancada. Solução prática para clínicas e hospitais veterinários que querem incorporar testes de coagulação à rotina.",
    ],
    specs: [
      { label: "Display", value: 'LCD 5,7"' },
      { label: "Canais", value: "2 (duplo)" },
      { label: "Incubadora integrada", value: "37 °C ± 0,2 °C" },
      { label: "Posições de amostra", value: "32 (2×16)" },
      { label: "Posições de reagente", value: "4 (2×2)" },
      { label: "Sistema de medição", value: "Fotométrico (óptico)" },
      { label: "Fonte de luz", value: "Lâmpada halógena" },
      { label: "Agitação", value: "Magnética na cubeta de medição" },
      { label: "Entrada de dados", value: "Teclado de membrana" },
      { label: "Impressora", value: "Térmica integrada, papel 58 mm" },
      { label: "Idiomas", value: "Português/inglês (outros sob demanda)" },
      { label: "Alimentação", value: "220V 50Hz / 110V 60Hz" },
      { label: "Dimensões", value: "30×40×15 cm · 5,5 kg" },
      { label: "Origem", value: "SHINOVA · China" },
    ],
  },
  {
    id: "urine",
    model: "UR-10V",
    category: "URINÁLISE",
    name: "Analisador de Urina Veterinário Portátil",
    shortName: "Analisador de Urina",
    productUrl: "https://www.shinova.com/product/detailp/Handheld-Veterinary-Urine-Analyzer",
    images: [
      "/products/urine.jpg",
      "/products/urine-2.jpg",
      "/products/urine-3.jpg",
      "/products/urine-4.jpg",
      "/products/urine-5.jpg",
      "/products/urine-6.jpg",
      "/products/urine-7.jpg",
      "/products/urine-8.jpg",
    ],
    description: [
      "O UR-10V é o analisador de urina veterinário portátil da Shinova, pequeno (110×68×27 mm) e leve (160 g), feito para urinálise rápida em clínicas, hospitais veterinários, laboratórios e fazendas. Cabe na palma da mão e roda com bateria de lítio recarregável.",
      "Lê 10 parâmetros por tira reagente: leucócitos (LEU), urobilinogênio (UBG), nitrito (NIT), proteína (PRO), pH, sangue (BLD), densidade (SG), cetona (KET), bilirrubina (BIL) e glicose (GLU). Faz análise automática dos dados e geração de laudo, com alta reprodutibilidade e resultados confiáveis.",
      "Tela LCD de 2,4\" com teclado por toque, throughput de até 300 testes/hora no modo rápido (60/hora no modo normal) e memória para 1.000 resultados. Impressora térmica sem fio opcional e interface mini-USB para exportação de dados.",
    ],
    specs: [
      { label: "Display", value: 'LCD 2,4" com teclado por toque' },
      { label: "Parâmetros (10)", value: "LEU, UBG, NIT, PRO, pH, BLD, SG, KET, BIL, GLU" },
      { label: "Throughput", value: "300 testes/h (rápido) · 60 testes/h (normal)" },
      { label: "Memória", value: "1.000 resultados" },
      { label: "Impressora", value: "Térmica sem fio (opcional)" },
      { label: "Interface", value: "Mini-USB" },
      { label: "Bateria", value: "Lítio DC 5V, 2A" },
      { label: "Carregador", value: "AC 100–240V, 50/60 Hz" },
      { label: "Peso líquido", value: "160 g" },
      { label: "Dimensões", value: "110×68×27 mm" },
      { label: "Origem", value: "SHINOVA · China" },
    ],
  },
];

export const analiseveterinaria: SiteConfig = {
  id: "analiseveterinaria",
  domain: "analiseveterinaria.com.br",
  lineName: "Linha Laboratorial",
  countWord: "7 analisadores",

  brand: {
    whatsapp: "5511943436177",
    phoneDisplay: "(11) 94343-6177",
    addressShort: "Vespasiano, MG",
    addressFull: "Av. Prefeito Sebastião Fernandes, 240 · Centro · Shopping Premiere · Vespasiano/MG",
    cnpj: "54.269.525/0001-56",
  },

  meta: {
    title: "Conecta · Análises Clínicas Veterinárias",
    description:
      "Analisadores laboratoriais veterinários, hematologia, bioquímica, gasometria, coagulação e urinálise. Representação oficial, suporte nacional, garantia 12 meses.",
  },

  topbarHtml:
    "🇧🇷 Distribuição oficial Shinova no Brasil · <strong>Representação oficial</strong> · Suporte técnico nacional",

  hero: {
    eyebrow: "Análises Clínicas Veterinárias",
    kicker: "Linha Laboratorial Premium · Distribuição Conecta · Fabricação Shinova",
    titleHtml: 'Laboratório veterinário completo, <em class="text-accent">com resultado na hora da decisão.</em>',
    subtitle:
      "Sete analisadores veterinários de hematologia, bioquímica, gasometria, coagulação e urinálise, com resultado rápido à beira do paciente, representação oficial e suporte técnico nacional.",
    bulletsHtml: [
      "Hematologia, bioquímica, gasometria, coagulação e urina em <strong>uma só linha</strong>",
      "Analisadores com <strong>parâmetros veterinários dedicados</strong>, multiespécie",
      "Representação oficial, <strong>sem intermediário inflando preço</strong>",
      "Suporte técnico nacional + garantia 12 meses + treinamento da equipe",
    ],
    ctaPrimary: "Ver os 7 analisadores",
    cardTag: "LINHA LABORATORIAL 2026",
    cardTitle: "Laboratório",
    cardImage: "/banco/analises-clinicas/veterinaria-coleta-sangue-cao.png",
    cardStats: [
      ["7", "Analisadores"],
      ["100%", "Representação oficial"],
      ["12 meses", "Garantia + suporte"],
    ],
    socialProofHtml:
      '<strong class="text-foreground">Mais de 300 clínicas e hospitais</strong> já operam com equipamentos distribuídos pela Conecta.',
  },

  benefits: {
    eyebrow: "Por que comprar Conecta",
    titleHtml:
      'Três razões pelas quais laboratórios veterinários <em class="text-accent">escolhem nossa distribuição.</em>',
    items: [
      {
        n: "i.",
        title: "Linha laboratorial completa, fornecedor único",
        p: "De hematologia a gasometria, sete analisadores que cobrem o laboratório veterinário em uma única origem. Você simplifica compra, treinamento, insumos e suporte. Sem vários fornecedores diferentes para montar o laboratório completo.",
      },
      {
        n: "ii.",
        title: "Parâmetros veterinários de origem",
        p: "Calibrados para fisiologia animal e multiespécie, cães, gatos, equinos, bovinos, suínos, exóticos, aves e répteis. Não é equipamento humano adaptado às pressas: são analisadores com perfis e faixas de referência dedicados à medicina veterinária.",
      },
      {
        n: "iii.",
        title: "Atendimento brasileiro",
        p: "Representação oficial sem intermediário. Suporte técnico nacional com resposta em até 4 horas úteis. Treinamento de uso à distância para sua equipe. Documentação fiscal completa. Garantia 12 meses respeitada pela própria Conecta, não terceirizada.",
      },
    ],
  },

  gallery: {
    eyebrow: "Linha laboratorial · 7 analisadores",
    titleHtml: 'Toque em qualquer analisador <em class="text-accent not-italic font-display italic">para explorar.</em>',
    subtitle:
      "Sete analisadores premium que cobrem hematologia, bioquímica, gasometria, coagulação e urinálise, fornecidos como linha integrada pela Conecta.",
  },

  applications: {
    eyebrow: "Aplicações",
    titleHtml: 'Onde a linha laboratorial Conecta <em class="text-accent">se encaixa na sua operação.</em>',
    cards: [
      {
        title: "Check-up e rotina laboratorial",
        p: "Hemograma completo + bioquímica clínica no fluxo do dia a dia. Combinação ideal: hematologia Hemo 3100V + bioquímica Chemo 120V para alto volume de exames.",
        img: "/banco/analises-clinicas/tecnico-analisador-hematologico.png",
      },
      {
        title: "Pré-cirúrgico e emergência",
        p: "Decisão rápida em UTI e centro cirúrgico. Gasometria e eletrólitos BG-800A + coagulômetro CL-202B para avaliar o paciente antes e durante o procedimento.",
        img: "/banco/analises-clinicas/leitura-analisador-bioquimico.png",
      },
      {
        title: "Atendimento à beira do paciente",
        p: "Resultado em minutos sem mandar para fora. Bioquímica portátil ChemoDisk 6 + analisador de urina UR-10V para consultório, campo e domicílio.",
        img: "/banco/analises-clinicas/gato-colo-coleta.png",
      },
      {
        title: "Diagnóstico de anemias e inflamação",
        p: "Hematologia avançada com reticulócitos para classificar anemias e avaliar resposta. Analisador 5-Diff Hemo 5100V para clínicas, hospitais e pesquisa.",
        img: "/banco/analises-clinicas/gasometria-amostra-sangue.png",
      },
    ],
  },

  testimonial: {
    quote:
      "Trocar três equipamentos de marcas diferentes por uma linha única de laboratório mudou nossa rotina. Hemograma, bioquímica e gasometria conversando entre si, com suporte nacional e treinamento da equipe. O resultado sai a tempo da decisão clínica.",
    name: "Dra. Marina Albuquerque",
    role: "Laboratório Veterinário Diagnóstico · Belo Horizonte/MG",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=120&q=80",
  },

  faq: [
    {
      q: "Posso comprar os 7 analisadores juntos ou só alguns?",
      a: "Pode comprar como achar melhor. Trabalhamos com pacote completo (com condição comercial diferenciada) e com aquisição parcial. Muitos laboratórios começam com hematologia + bioquímica e expandem ao longo de 6-12 meses. Faz orçamento da configuração que faz sentido para sua operação atual.",
    },
    {
      q: "Qual o prazo de entrega?",
      a: "Prazo de entrega de 60 a 90 dias. São equipamentos importados de alta tecnologia, produzidos sob demanda, por isso o prazo reflete a fabricação e a representação oficial, sem intermediário inflando preço. Todo equipamento chega instalado, comissionado, calibrado e com treinamento operacional incluso.",
    },
    {
      q: "E os reagentes e insumos de cada analisador?",
      a: "Orientamos sobre os reagentes, tiras, discos e cubetas compatíveis com cada analisador e as opções de reposição. Detalhamos consumo e custo por teste na proposta personalizada, para você dimensionar a operação com clareza.",
    },
    {
      q: "Os equipamentos têm certificação Anvisa?",
      a: "Os equipamentos têm certificação CE (Conformidade Europeia) e ISO 13485 do fabricante. Para uso exclusivamente veterinário no Brasil não há exigência de registro Anvisa. Fornecemos toda a documentação fiscal e técnica que acompanha cada equipamento.",
    },
    {
      q: "Vocês entregam em todo o Brasil?",
      a: "Sim, cobertura nacional nas 26 UFs + Distrito Federal. Transportadora especializada em equipamento médico-hospitalar com seguro completo. Coordenamos a instalação técnica e o treinamento da equipe.",
    },
  ],

  quote: {
    titleHtml: 'Cada laboratório é único. <em class="text-accent">Sua proposta também precisa ser.</em>',
    subtitle:
      "Conta o que você precisa equipar, hematologia, bioquímica, gasometria ou tudo junto. Devolvemos uma proposta sob medida com analisadores, insumos, treinamento e condições.",
    bulletsHtml: [
      "Resposta em até 4 horas úteis, direto com nossa equipe técnica",
      "Proposta personalizada com analisadores, insumos, treinamento e condições",
      "Sem compromisso de compra, se não fizer sentido para você, sem problema.",
      "Dados confidenciais, suas informações não vão fora da Conecta",
    ],
    stats: [
      ["~4h", "tempo médio de resposta"],
      ["300+", "clientes atendidos"],
    ],
    packageLabel: "Pacote completo (todos os 7)",
  },

  footerCatalog: [
    "Hematologia",
    "Bioquímica",
    "Bioquímica portátil",
    "Gasometria e eletrólitos",
    "Coagulação",
    "Urinálise",
    "Reagentes e insumos",
  ],
  footerBlurb:
    "Distribuição oficial de equipamentos veterinários premium. Representação oficial, suporte técnico nacional, garantia respeitada.",

  products: labProducts,
};
