import type { Product } from "./types";

const CE = "SHINOVA · China · CE/ISO 13485";

export const dopscan10v: Product = {
  id: "dopscan-10v",
  model: "DopScan 10V",
  category: "ULTRASSOM DOPPLER",
  name: "Sistema de Ultrassom Color Doppler Veterinário",
  shortName: "Color Doppler",
  productUrl: "https://www.shinova.com/product/detailp/Veterinary-Color-Doppler-System-DopScan-10V",
  images: [
    "/products/dopscan-10v.jpg",
    "/products/dopscan-10v-2.jpg",
    "/products/dopscan-10v-3.jpg",
    "/products/dopscan-10v-4.jpg",
    "/products/dopscan-10v-5.jpg",
    "/products/dopscan-10v-6.jpg",
    "/products/dopscan-10v-7.jpg",
    "/products/dopscan-10v-8.jpg",
  ],
  description: [
    "O DopScan 10V é o sistema de ultrassom color doppler veterinário da linha Shinova, plataforma totalmente digital com síntese multifeixe e foco dinâmico ponto a ponto em tempo real. Imagem harmônica por inversão de pulso e composição espacial entregam imagem nítida com redução de ruído.",
    "Acompanha disco rígido interno de 500 GB com estação de trabalho integrada para buscar e navegar nos dados dos pacientes, além de bateria de lítio interna para mobilidade. Software de medição e cálculo robusto para demanda clínica e compatibilidade DICOM 3.0 para integração com o fluxo de imagem.",
    "Configuração padrão com transdutor micro-convexo 6.5 MHz e linear 7.5 MHz; opcionais incluem convexo multifrequência 3.5 MHz e linear retal 6.5 MHz, cobrindo aplicações abdominais, cardíacas, reprodutivas e de pequenas estruturas. Armazena imagens (JPG, BMP, FRM) e vídeos (CIN, AVI).",
  ],
  specs: [
    { label: "Tecnologia de imagem", value: "Totalmente digital, síntese multifeixe" },
    { label: "Foco", value: "Dinâmico ponto a ponto em tempo real" },
    { label: "Recursos de imagem", value: "Harmônica por inversão de pulso, composição espacial, redução de ruído" },
    { label: "Modo", value: "Color Doppler" },
    { label: "Transdutor convexo (padrão)", value: "Micro-convexo 6.5 MHz" },
    { label: "Transdutor linear (padrão)", value: "7.5 MHz" },
    { label: "Transdutores opcionais", value: "Convexo multifrequência 3.5 MHz · Linear retal 6.5 MHz" },
    { label: "Armazenamento", value: "HD interno ≥ 500 GB + estação de trabalho" },
    { label: "Padrão de imagem", value: "DICOM 3.0" },
    { label: "Formatos", value: "Imagem JPG/BMP/FRM · Vídeo CIN/AVI" },
    { label: "Bateria", value: "Lítio interna" },
    { label: "Opcionais", value: "Impressora USB, impressora de vídeo, guia de biópsia, carrinho, pedal" },
    { label: "Origem", value: CE },
  ],
};

export const sonoscanE6V: Product = {
  id: "sonoscan-e6v",
  model: "SonoScan E6V",
  category: "ULTRASSOM PORTÁTIL",
  name: "Ultrassom Veterinário Portátil",
  shortName: "Ultrassom Portátil",
  productUrl: "https://www.shinova.com/product/detailp/Portable-Vet-Ultrasound-SonoScan-E6V",
  images: [
    "/products/sonoscan-e6v.jpg",
    "/products/sonoscan-e6v-2.jpg",
    "/products/sonoscan-e6v-3.jpg",
    "/products/sonoscan-e6v-4.jpg",
    "/products/sonoscan-e6v-5.jpg",
    "/products/sonoscan-e6v-6.jpg",
    "/products/sonoscan-e6v-7.jpg",
    "/products/sonoscan-e6v-8.jpg",
  ],
  description: [
    "O SonoScan E6V é o ultrassom veterinário super portátil da Shinova, duplo modo de alimentação (rede AC ou bateria de 4400 mAh com mais de 200 minutos de operação) para trabalhar em qualquer lugar. Tela LED colorida de 10,4\" de alta resolução, alto contraste e amplo ângulo de visão, com monitor giratório para ajustar o ângulo.",
    "Sistema de controle ARM7 embarcado com processamento de sinais FPGA. Dois conectores de transdutor com identificação automática, 64 marcas corporais e modos de display B, 2B, 4B, B/M e M. Frequência de quadros de 30 fps, escala de 256 tons de cinza, TGC inteligente de 8 passos e profundidade ajustável em 10 níveis (até 236 mm).",
    "Armazena cerca de 5.000 imagens (HD 4 GB), cine loop de 256 quadros e duas linhas de punção corrigíveis. Software de medição com OB (idade gestacional para várias espécies) e análise urológica. Leve (4,5 kg), com interface em português. Indicado para sala de exame e centro cirúrgico.",
  ],
  specs: [
    { label: "Display", value: 'LED colorido 10,4" alta resolução, amplo ângulo' },
    { label: "Sistema de controle", value: "ARM7 embarcado + processamento FPGA" },
    { label: "Conectores de transdutor", value: "2 (identificação automática)" },
    { label: "Modos de display", value: "B, 2B, 4B, B/M, M" },
    { label: "Profundidade", value: "10 níveis, máx. 236 mm" },
    { label: "Faixa de contraste", value: "27–90 dB" },
    { label: "Escala de cinza", value: "256" },
    { label: "TGC", value: "8 passos inteligente" },
    { label: "Frequência de quadros", value: "30 fps" },
    { label: "Armazenamento", value: "HD 4 GB (~5.000 imagens)" },
    { label: "Cine loop", value: "256 quadros" },
    { label: "Guia de punção", value: "2 linhas corrigíveis" },
    { label: "Medições", value: "Software OB (multiespécie) e urologia" },
    { label: "Idiomas", value: "Português, inglês, espanhol, francês, russo" },
    { label: "Alimentação", value: "AC 100–240V / bateria 4400 mAh (>200 min)" },
    { label: "Dimensões", value: "256×150×326 mm · 4,5 kg" },
    { label: "Origem", value: CE },
  ],
};

export const sonoscanB5V: Product = {
  id: "sonoscan-b5v",
  model: "SonoScan B5V",
  category: "ULTRASSOM PORTÁTIL",
  name: "Ultrassom Veterinário de Mão",
  shortName: "Ultrassom de Mão",
  productUrl: "https://www.shinova.com/product/detailp/Handheld-Ultrasound-SonoScan-B5V",
  images: [
    "/products/sonoscan-b5v.jpg",
    "/products/sonoscan-b5v-2.jpg",
    "/products/sonoscan-b5v-3.jpg",
    "/products/sonoscan-b5v-4.jpg",
    "/products/sonoscan-b5v-5.jpg",
    "/products/sonoscan-b5v-6.jpg",
    "/products/sonoscan-b5v-7.jpg",
    "/products/sonoscan-b5v-8.jpg",
  ],
  description: [
    "O SonoScan B5V é o ultrassom veterinário de mão (handheld) da Shinova, ultraleve (0,48 kg), compacto e ergonômico, projetado especialmente para grandes rebanhos: porcas, ovelhas, cabras e bovinos de leite e corte. Excelente qualidade de imagem para detecção rápida e confiável.",
    "Diagnóstico de gestação precoce, a partir do 19º dia em porcas, 28º em bovinos e 25º em ovinos e caprinos. Tela LCD WVGA de 5,8\" com amplo ângulo de visão (que pode ser desligada ao usar os óculos de vídeo opcionais). USB 2.0 para transferir imagens e vídeos ao computador, cine loop de 450–550 quadros e 150 imagens internas.",
    "Bateria de lítio com 5,5–6,5 horas de operação (acompanha duas baterias para uso contínuo), alça de ombro para liberdade de movimento e capa de couro lavável, resistente às condições severas do campo. Software e relatório para sistema reprodutivo, com medições de distância, área, circunferência, volume, ângulo e frequência cardíaca. Aplicações: bovinos, equinos, suínos, ovinos, caprinos, cães e gatos.",
  ],
  specs: [
    { label: "Tipo", value: "Handheld (de mão), ultraportátil" },
    { label: "Peso", value: "0,48 kg" },
    { label: "Display", value: 'LCD WVGA 5,8" amplo ângulo (desligável c/ óculos de vídeo)' },
    { label: "Conectividade", value: "USB 2.0 (transferência para PC)" },
    { label: "Cine loop", value: "450–550 quadros · 150 imagens internas" },
    { label: "Bateria", value: "Lítio 5,5–6,5 h (2 baterias inclusas)" },
    { label: "Diagnóstico de gestação", value: "Porcas 19º dia · Bovinos 28º · Ovinos/caprinos 25º" },
    { label: "Software", value: "Reprodução + medições (distância, área, circunferência, volume, ângulo, FC)" },
    { label: "Proteção", value: "Capa de couro lavável, resistente a campo" },
    { label: "Óculos de vídeo", value: "Opcional" },
    { label: "Aplicações", value: "Bovinos, equinos, suínos, ovinos, caprinos, cães, gatos" },
    { label: "Origem", value: CE },
  ],
};
