import type { Product } from "./types";

// Linha cirúrgica (7 equipamentos), usada pelo site cirugiavet.
export const products: Product[] = [
  {
    id: "anecompact",
    model: "AneCompact-C",
    category: "ANESTESIA",
    name: "Aparelho de Anestesia Veterinária Portátil",
    shortName: "Anestesia Portátil",
    productUrl: "https://www.shinova.com/product/detailp/Exotic-Animal-Anesthesia-Machine",
    images: [
      "/products/anecompact.jpg",
      "/products/anecompact-2.jpg",
      "/products/anecompact-3.jpg",
      "/products/anecompact-4.jpg",
      "/products/anecompact-5.jpg",
      "/products/anecompact-6.jpg",
      "/products/anecompact-7.jpg",
      "/products/anecompact-8.jpg",
    ],
    description: [
      "O AneCompact-C é o aparelho de anestesia veterinária portátil da linha Shinova para animais exóticos e pequenos pacientes. Compacto, estável e altamente confiável, foi projetado para clínicas que precisam de uma solução portátil sem abrir mão de funcionalidade profissional cirúrgica.",
      "Equipamento ideal para centros de medicina veterinária, hospitais, clínicas, zoológicos e centros de pesquisa. Suporta múltiplos modos respiratórios e aceita vaporizadores de Isoflurano, Sevoflurano, Halotano e Enflurano. Sistema de absorção de CO₂ integrado com câmara de cal sodada de troca rápida.",
      "Estrutura compacta com alça superior facilita transporte entre salas. Quatro bases de apoio permitem instalação em qualquer superfície plana, mesa, carrinho ou estação cirúrgica. Pode ser usado em ambulâncias móveis, clínicas dentárias veterinárias e atendimentos onde o espaço é limitado.",
    ],
    specs: [
      { label: "Pressão de trabalho de oxigênio", value: "0.3–0.4 MPa" },
      { label: "Controle de fluxo de oxigênio", value: "0.1–10 L/min" },
      { label: "Flush de oxigênio", value: "40–70 L/min" },
      { label: "Volume da câmara de cal sodada", value: "1000 mL" },
      { label: "Vaporizador", value: "Faixa de ajuste 0.2–5 VoL%" },
      { label: "Proteção de pressão de pico", value: "60 cmH₂O" },
      { label: "Válvula APL", value: "-5 a 60 cmH₂O" },
      { label: "Volume corrente", value: "20–1500 mL" },
      { label: "Pacientes", value: "A partir de 3 kg" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
  {
    id: "lifesaver-t",
    model: "LifeSaver-T",
    category: "VENTILAÇÃO ANESTÉSICA",
    name: "Ventilador Anestésico Veterinário Turbo Inteligente",
    shortName: "Ventilador Anestésico",
    productUrl: "https://www.shinova.com/product/detailp/Intelligent-Turbo-driven-Veterinary-Anesthesia-Ventilator-LifeSaver-T",
    images: [
      "/products/lifesaver-t.jpg",
      "/products/lifesaver-t-2.jpg",
      "/products/lifesaver-t-3.jpg",
      "/products/lifesaver-t-4.jpg",
      "/products/lifesaver-t-5.jpg",
      "/products/lifesaver-t-6.jpg",
      "/products/lifesaver-t-7.jpg",
      "/products/lifesaver-t-8.jpg",
    ],
    description: [
      "O LifeSaver-T é o ventilador anestésico veterinário com tecnologia turbo da linha Shinova, projetado para cirurgias de pequeno, médio e grande porte. Tecnologia turbo dispensa fonte de ar comprimido de alta pressão: basta um concentrador de oxigênio para operar, simplificando instalação e reduzindo custo de infraestrutura.",
      "Os parâmetros de ventilação são calculados automaticamente apenas inserindo o peso do animal, operação simplificada que reduz erro humano em momento crítico. Modos VCV (controle por volume), PCV (controle por pressão), SPONT (espontâneo) e SIMV cobrem todos os cenários clínicos. Modo SPONT inteligente evita confronto respiratório, ideal para recuperação.",
      "PEEP elétrico ajustável, alarme de apneia configurável, monitoramento de fluxo respiratório proximal para maior precisão. Foles para animais grandes e pequenos intercambiáveis. Tela touch TFT HD com teclas táteis. Compatível com aparelhos de anestesia de diversas marcas. Leve e fácil de mover, otimiza espaço hospitalar.",
    ],
    specs: [
      { label: "Volume corrente (TV)", value: "20–1500 mL" },
      { label: "Frequência respiratória", value: "1–150 bpm" },
      { label: "Frequência espontânea", value: "0–150 bpm" },
      { label: "Relação I:E", value: "9.9:1 a 1:9 ajustável" },
      { label: "Tempo de hold", value: "0–50%" },
      { label: "Sensibilidade trigger de fluxo", value: "0.5–20 L/min ou OFF" },
      { label: "Sensibilidade trigger de pressão", value: "-1 a 20 cmH₂O ou OFF" },
      { label: "PEEP", value: "3–20 cmH₂O ou OFF" },
      { label: "Frequência SIMV", value: "2–60 bpm" },
      { label: "Tempo inspiratório", value: "0.1–12 s" },
      { label: "Pressão de suporte (PS)", value: "0–60 cmH₂O" },
      { label: "FiO₂", value: "15–100%" },
      { label: "Modos", value: "VCV, PCV, SPONT, SIMV, Manual" },
      { label: "Display", value: "TFT HD touchscreen" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
  {
    id: "moni-3l",
    model: "Moni 3L",
    category: "MONITORAMENTO",
    name: 'Monitor Multiparâmetros Veterinário Touchscreen 15"',
    shortName: "Monitor Multiparâmetros",
    productUrl: "https://www.shinova.com/product/detailp/15-inch-Touchscreen-Modular-Veterinary-Monitor",
    images: [
      "/products/moni-3l.jpg",
      "/products/moni-3l-2.jpg",
      "/products/moni-3l-3.jpg",
      "/products/moni-3l-4.jpg",
      "/products/moni-3l-5.jpg",
      "/products/moni-3l-6.jpg",
      "/products/moni-3l-7.jpg",
      "/products/moni-3l-8.jpg",
    ],
    description: [
      "O Moni 3L é o monitor multiparâmetros veterinário de referência da linha Shinova, touchscreen de 15 polegadas LCD alto brilho com efeito espelhado, proporcionando visualização superior em qualquer condição de luz cirúrgica. Equipamento dedicado para centro cirúrgico, UTI, internação e consultório.",
      "Três modos clínicos integrados, diagnóstico, monitoramento e cirúrgico, adaptados a pets de grande, médio e pequeno porte. Múltiplos modos de display: padrão, grande caractere (leitura à distância), gráfico de tendência e lista de pressão arterial. Suporta exibição multi-derivação de ECG simultaneamente na mesma tela.",
      "Acompanha manguito de pressão arterial específico veterinário para medição precisa em pets de portes variados. Múltiplas funções de análise, alarmes configuráveis em setup rápido. Bateria de lítio de alta capacidade integrada com longa autonomia em standby, ideal para cirurgias prolongadas ou transporte entre salas.",
    ],
    specs: [
      { label: "Display", value: '15" LCD touchscreen alto brilho com efeito espelhado' },
      { label: "Modos clínicos", value: "Diagnóstico · Monitoramento · Cirúrgico" },
      { label: "Modos de display", value: "Padrão, Grande caractere, Tendência, Lista NIBP" },
      { label: "ECG", value: "Multi-derivação simultânea" },
      { label: "NIBP", value: "Manguito veterinário (pequeno, médio, grande)" },
      { label: "SpO₂", value: "Probe veterinária dedicada" },
      { label: "Temperatura", value: "2 canais" },
      { label: "Funções", value: "Múltiplas análises, alarmes configuráveis" },
      { label: "Bateria", value: "Lítio alta capacidade, autonomia prolongada" },
      { label: "Pets aplicáveis", value: "Grande, médio e pequeno porte" },
      { label: "Aplicações", value: "Sala cirúrgica, UTI, internação, consultório" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
  {
    id: "dm8d-ii",
    model: "DM8D-II",
    category: "EMERGÊNCIA",
    name: "Desfibrilador Bifásico Portátil Veterinário",
    shortName: "Desfibrilador Bifásico",
    productUrl: "https://www.shinova.com/product/detailp/Veterinary-Portable-Biphasic-Defibrillator-DM8D-II",
    images: [
      "/products/dm8d-ii.jpg",
      "/products/dm8d-ii-2.jpg",
      "/products/dm8d-ii-3.jpg",
      "/products/dm8d-ii-4.jpg",
      "/products/dm8d-ii-5.jpg",
      "/products/dm8d-ii-6.jpg",
      "/products/dm8d-ii-7.jpg",
      "/products/dm8d-ii-8.jpg",
    ],
    description: [
      "O DM8D-II é o desfibrilador bifásico portátil veterinário Shinova, versão atualizada com gravador integrado padrão, bateria de lítio-íon padrão e prompts por voz. Equipamento essencial para centro cirúrgico, UTI veterinária e atendimento de emergência cardiovascular.",
      "Tecnologia bifásica entrega choque com energia ajustável de 0 a 360 joules em 12 níveis. Carga rápida, até 360J em menos de 10 segundos. Modos sincronizado e não-sincronizado para cardioversão e desfibrilação manual externa. Forma de onda ECG via eletrodo de pá permite leitura imediata sem cabos extras.",
      "Tela TFT colorida 7\" de alta resolução 800×480 com velocidade de varredura ajustável. Bateria oferece até 10 horas de monitoramento ECG contínuo ou 60 descargas em energia máxima. Gravador térmico integrado registra disparo da descarga, alarmes de FC e modo automático cronometrado. SpO₂ disponível como módulo opcional.",
    ],
    specs: [
      { label: "Display", value: 'TFT colorido 7" (17.7 cm), resolução 800×480' },
      { label: "Velocidade de varredura", value: "12.5 / 25 / 50 mm/s" },
      { label: "ECG", value: "Cabos 3-vias ou 5-vias + pás" },
      { label: "Derivações", value: "I, II, III, AVR, AVL, AVF, V" },
      { label: "Frequência cardíaca", value: "20–350 BPM" },
      { label: "Forma de onda", value: "Bifásica" },
      { label: "Tipo", value: "Manual externo síncrono/assíncrono" },
      { label: "Tempo de carga", value: "<10 s até 360J" },
      { label: "Energia", value: "0, 3, 5, 7, 10, 20, 30, 50, 100, 200, 300, 360 J" },
      { label: "Pás", value: "Reutilizáveis adulto/infantil integradas" },
      { label: "Bateria", value: "Lítio-íon Li1104c 11.1Vdc 4000mAh × 2" },
      { label: "Autonomia", value: "10h ECG ou 60 descargas máximas" },
      { label: "Gravador", value: "Térmico 50mm integrado padrão" },
      { label: "Alimentação", value: "AC 100–240V 50/60Hz ou DC 12V (opcional)" },
      { label: "SpO₂", value: "Módulo opcional" },
      { label: "Prompts", value: "Voz + visuais" },
      { label: "Dimensões", value: "L320×W205×H410 mm · 7.5 kg" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
  {
    id: "led-lamp",
    model: "LEDBL-7070",
    category: "ILUMINAÇÃO CIRÚRGICA",
    name: "Foco Cirúrgico LED Shadowless Veterinário",
    shortName: "Foco Cirúrgico LED",
    productUrl: "https://www.shinova.com/product/detailp/Shadowless-Operating-Lamp-veterinary",
    images: [
      "/products/led-lamp.jpg",
      "/products/led-lamp-2.jpg",
      "/products/led-lamp-3.jpg",
      "/products/led-lamp-4.jpg",
      "/products/led-lamp-5.jpg",
      "/products/led-lamp-6.jpg",
      "/products/led-lamp-7.jpg",
      "/products/led-lamp-8.jpg",
    ],
    description: [
      "O LEDBL-7070 é o foco cirúrgico LED sem sombras (shadowless) da linha Shinova, projetado para iluminação uniforme e homogênea em procedimentos superficiais e cavidades profundas. Sistema óptico reflexivo fabricado por tecnologia CAD/CAM com profundidade de iluminação até 1300 mm.",
      "Tecnologia de compensação de temperatura de cor entrega reprodução cromática precisa (Ra 95), fundamental para cirurgias complexas como encefálicas e torácicas onde diferenciar tecidos é crítico. Painel construído em PC alemão (plástico à prova de impacto) por injeção, deixando a luz mais suave e o equipamento mais durável.",
      "Sistema de braço de balanço importado, leve e prático, com 6 grupos de articulações que se movem em conjunto suavemente, posicionamento estável e design universal 360° atende qualquer altura ou ângulo. Temperatura de cor ajustável em 3 níveis (3800K, 4400K, 5000K) reduz fadiga visual da equipe cirúrgica.",
    ],
    specs: [
      { label: "Iluminância", value: "≥160.000 Lux" },
      { label: "Temperatura de cor", value: "3800K / 4400K / 5000K (3 níveis)" },
      { label: "Variação", value: "±500K" },
      { label: "Índice cromático (Ra)", value: "95" },
      { label: "Profundidade de iluminação", value: "≥1300 mm" },
      { label: "Irradiação total", value: "450 W/m²" },
      { label: "Tamanho do campo de luz", value: "160–280 mm" },
      { label: "Vida útil do LED", value: "50.000 horas" },
      { label: "Tensão", value: "AC 110–240V 50/60Hz" },
      { label: "Altura mínima de instalação", value: "2900 mm" },
      { label: "Consumo total", value: "160 W" },
      { label: "Quantidade de LEDs", value: "216 unidades (2×108)" },
      { label: "Painel", value: "PC alemão (anti-impacto) por injeção" },
      { label: "Sistema óptico", value: "Reflexivo CAD/CAM" },
      { label: "Movimento", value: "360° universal, 6 articulações" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
  {
    id: "ls-120a",
    model: "LS-120A",
    category: "CIRURGIA AVANÇADA",
    name: "Gerador de Bisturi Ultrassônico Veterinário",
    shortName: "Bisturi Ultrassônico",
    productUrl: "https://www.shinova.com/product/detailp/Veterianry-Ultrasonic-Scalpel-Generator-LS-120A",
    images: [
      "/products/ls-120a.jpg",
      "/products/ls-120a-2.jpg",
      "/products/ls-120a-3.jpg",
      "/products/ls-120a-4.jpg",
      "/products/ls-120a-5.jpg",
      "/products/ls-120a-6.jpg",
      "/products/ls-120a-7.jpg",
      "/products/ls-120a-8.jpg",
    ],
    description: [
      "O LS-120A é o gerador de bisturi ultrassônico veterinário Shinova, equipamento de cirurgia avançada projetado para procedimentos onde precisão de corte e selamento são críticos. Aplicações principais: cirurgia geral (gastrointestinal alta, colorretal, hepatobiliar, bariátrica veterinária), ginecologia, urologia e cirurgia torácica.",
      "Tecnologia ultrassônica de alta frequência (55.5 kHz) entrega corte preciso com hemostasia simultânea, reduz tempo de cirurgia e perda sanguínea. Display LCD 7\" para controle visual completo dos parâmetros operatórios. Equipamento certificado IIb pela diretiva 93/42/EEC e tipo CF segundo EN 60601-1.",
      "Vasos menores que 3mm são selados com segurança durante a operação, com selamento máximo até 5mm. Multifuncional: hemostasia, corte, preensão e dissecção em um único instrumento, reduzindo substituições intraoperatórias.",
    ],
    specs: [
      { label: "Frequência de rede", value: "50/60 Hz" },
      { label: "Tensão de rede", value: "100–240V (±10%)" },
      { label: "Fusível principal", value: "T5AH 250V (2 unidades)" },
      { label: "Consumo máximo", value: "150 VA" },
      { label: "Dimensões", value: "350×355×136 mm" },
      { label: "Peso", value: "7.6 kg" },
      { label: "Display", value: 'LCD 7"' },
      { label: "Classificação EC Directive 93/42/EEC", value: "IIb" },
      { label: "Classe de proteção EN 60601-1", value: "I" },
      { label: "Tipo (EN 60601-1)", value: "CF" },
      { label: "Frequência de saída", value: "55.5 ±0.5 kHz" },
      { label: "Potência de saída", value: "35W (máxima contínua)" },
      { label: "Potência máxima", value: "120 W" },
      { label: "Aplicações", value: "Cirurgia geral, ginecologia, urologia, torácica" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
  {
    id: "ls-150",
    model: "LS-150",
    category: "CIRURGIA AVANÇADA",
    name: "Gerador de Selamento de Vasos & Unidade Eletrocirúrgica (LigaSure & ESU)",
    shortName: "Vessel Sealing & ESU",
    productUrl: "https://www.shinova.com/product/detailp/Veterinary-Vessel-Sealing-Generator-and-Electrosurgical-Unit",
    images: [
      "/products/ls-150.jpg",
      "/products/ls-150-2.jpg",
      "/products/ls-150-3.jpg",
      "/products/ls-150-4.jpg",
      "/products/ls-150-5.jpg",
      "/products/ls-150-6.jpg",
      "/products/ls-150-7.jpg",
      "/products/ls-150-8.jpg",
    ],
    description: [
      "O LS-150 é um equipamento 2-em-1 da linha Shinova: gerador de selamento de vasos (vessel sealing / LigaSure) combinado com unidade eletrocirúrgica (ESU) veterinária. Plataforma intuitiva com tela touchscreen TFT LCD 7\", todas as configurações e modos são alterados tocando ícones, garantindo operação máxima em sala cirúrgica.",
      "Tecnologia proprietária de monitoramento de impedância tecidual em tempo real: amostra corrente e tensão 450.000 vezes por segundo, respondendo a mudanças teciduais em menos de 10 milissegundos. Isso garante saída de energia precisa para cada tipo de tecido, somente a tensão exata necessária é entregue. Funções mono e bipolar atendem todas as demandas cirúrgicas.",
      "Sistema REM (Return Electrode Monitoring) monitora continuamente a impedância do paciente e desativa o gerador se houver falha de contato, minimiza incidentes de queimadura. Selamento permanente de vasos com diâmetro até 7mm via coagulação bipolar LigaSure. Autoteste interno completo ao ligar.",
    ],
    specs: [
      { label: "Frequência principal", value: "512 kHz" },
      { label: "Alimentação", value: "100–240V / 50–60Hz" },
      { label: "Dimensões", value: "47×34×17 cm" },
      { label: "Peso", value: "8.00 kg" },
      { label: "Vazamento monopolar", value: "<150 mA" },
      { label: "Vazamento bipolar", value: "<60 mA" },
      { label: "Corte monopolar puro", value: "150W (500Ω)" },
      { label: "Corte misto I", value: "120W (500Ω)" },
      { label: "Corte misto II", value: "100W (500Ω)" },
      { label: "Coagulação fulgurada", value: "120W (500Ω)" },
      { label: "Coagulação spray", value: "100W (500Ω)" },
      { label: "Coagulação bipolar padrão", value: "80W (100Ω)" },
      { label: "LigaSure Vessel Sealing", value: "150W (20Ω)" },
      { label: "Display", value: 'TFT LCD 7" touchscreen' },
      { label: "Selamento vascular", value: "Até 7mm de diâmetro" },
      { label: "Sistema REM", value: "Monitoramento contínuo de impedância" },
      { label: "Autoteste", value: "Completo ao ligar" },
      { label: "Funções", value: "Monopolar + Bipolar + Vessel Sealing" },
      { label: "Origem", value: "SHINOVA · China · CE/ISO 13485" },
    ],
  },
];
