/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProdutosCategoriaSlugRouteImport } from './routes/produtos.categoria.$slug'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosCategoriaSlugRoute = ProdutosCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos/categoria/$slug': typeof ProdutosCategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/produtos/categoria/$slug': typeof ProdutosCategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos/categoria/$slug': typeof ProdutosCategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/solucoes'
    | '/admin/login'
    | '/produtos/$slug'
    | '/admin/'
    | '/produtos/categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/solucoes'
    | '/admin/login'
    | '/produtos/$slug'
    | '/admin'
    | '/produtos/categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/solucoes'
    | '/admin/login'
    | '/produtos/$slug'
    | '/admin/'
    | '/produtos/categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos/categoria/$slug': {
      id: '/produtos/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/produtos/categoria/$slug'
      preLoaderRoute: typeof ProdutosCategoriaSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosCategoriaSlugRoute: typeof ProdutosCategoriaSlugRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosCategoriaSlugRoute: ProdutosCategoriaSlugRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
