/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as BlogEnviarRouteImport } from './routes/blog.enviar'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminPaginaInicialRouteImport } from './routes/admin.pagina-inicial'
import { Route as AdminOrcamentosRouteImport } from './routes/admin.orcamentos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormulariosRouteImport } from './routes/admin.formularios'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as ProdutosCategoriaSlugRouteImport } from './routes/produtos.categoria.$slug'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventosRoute,
} as any)
const BlogEnviarRoute = BlogEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginaInicialRoute = AdminPaginaInicialRouteImport.update({
  id: '/pagina-inicial',
  path: '/pagina-inicial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormulariosRoute = AdminFormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosCategoriaSlugRoute = ProdutosCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/formularios': typeof AdminFormulariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pagina-inicial': typeof AdminPaginaInicialRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/enviar': typeof BlogEnviarRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos/categoria/$slug': typeof ProdutosCategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/formularios': typeof AdminFormulariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pagina-inicial': typeof AdminPaginaInicialRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/enviar': typeof BlogEnviarRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/produtos/categoria/$slug': typeof ProdutosCategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/formularios': typeof AdminFormulariosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pagina-inicial': typeof AdminPaginaInicialRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/enviar': typeof BlogEnviarRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos/categoria/$slug': typeof ProdutosCategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/contato'
    | '/eventos'
    | '/produtos'
    | '/sobre'
    | '/solucoes'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/eventos'
    | '/admin/formularios'
    | '/admin/login'
    | '/admin/orcamentos'
    | '/admin/pagina-inicial'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/blog/$slug'
    | '/blog/enviar'
    | '/eventos/$slug'
    | '/produtos/$slug'
    | '/admin/'
    | '/produtos/categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/eventos'
    | '/produtos'
    | '/sobre'
    | '/solucoes'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/eventos'
    | '/admin/formularios'
    | '/admin/login'
    | '/admin/orcamentos'
    | '/admin/pagina-inicial'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/blog/$slug'
    | '/blog/enviar'
    | '/eventos/$slug'
    | '/produtos/$slug'
    | '/admin'
    | '/produtos/categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/contato'
    | '/eventos'
    | '/produtos'
    | '/sobre'
    | '/solucoes'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/eventos'
    | '/admin/formularios'
    | '/admin/login'
    | '/admin/orcamentos'
    | '/admin/pagina-inicial'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/blog/$slug'
    | '/blog/enviar'
    | '/eventos/$slug'
    | '/produtos/$slug'
    | '/admin/'
    | '/produtos/categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EventosRoute: typeof EventosRouteWithChildren
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof EventosRoute
    }
    '/blog/enviar': {
      id: '/blog/enviar'
      path: '/enviar'
      fullPath: '/blog/enviar'
      preLoaderRoute: typeof BlogEnviarRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagina-inicial': {
      id: '/admin/pagina-inicial'
      path: '/pagina-inicial'
      fullPath: '/admin/pagina-inicial'
      preLoaderRoute: typeof AdminPaginaInicialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formularios': {
      id: '/admin/formularios'
      path: '/formularios'
      fullPath: '/admin/formularios'
      preLoaderRoute: typeof AdminFormulariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos/categoria/$slug': {
      id: '/produtos/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/produtos/categoria/$slug'
      preLoaderRoute: typeof ProdutosCategoriaSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminFormulariosRoute: typeof AdminFormulariosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminPaginaInicialRoute: typeof AdminPaginaInicialRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminFormulariosRoute: AdminFormulariosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminPaginaInicialRoute: AdminPaginaInicialRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogEnviarRoute: typeof BlogEnviarRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogEnviarRoute: BlogEnviarRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventosRouteChildren {
  EventosSlugRoute: typeof EventosSlugRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosSlugRoute: EventosSlugRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosCategoriaSlugRoute: typeof ProdutosCategoriaSlugRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosCategoriaSlugRoute: ProdutosCategoriaSlugRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EventosRoute: EventosRouteWithChildren,
  ProdutosRoute: ProdutosRouteWithChildren,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
